# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         BIND-Config-Parser
version:      0.01
version_from: lib/BIND/Config/Parser.pm
installdirs:  site
requires:
    Parse::RecDescent:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
